name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Build
      run: go build -v cmd/webhook/main.go
    - name: pretest
      run: cd e2e/pretest &&  ./env_setup.sh
    - name: Test
      run: go test -v ./... -tags e2e

  e2e-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: modify host
      run: cd e2e/pretest && sudo ./modify_host.sh
    - name: pretest
      run: cd e2e/pretest &&  ./env_setup.sh
    - name: run e2e test
      run: cd e2e && ./test.sh
